version: "3"
services:
  app:
    container_name: express
    restart: always
    image: regularlemon/cinema_tracker_app:latest
    ports:
      - "5000:5000"
    environment:
      - DEBUG_OLDEN=1
      - DATABASE
      - DATABASE_USER
      - DATABASE_PASSWORD
      - DATABASE_HOSTNAME
      - DATABASE_PORT
    command: ["./run.sh"]
  nginx:
    build: ./nginx
    tty: true
    links:
      - app
    ports:
      - "80:8080"
