version: "3"
services:
  app:
    container_name: express
    restart: always
    image: regularlemon/cinema_tracker_app:latest
    ports:
      - "5000:5000"
    env_file:
      - env-variables.env
    command: ["./run.sh"]
    networks:
      - darbar_load_balancer
networks:
  darbar_load_balancer:
    external: true
