version: "2.4"
services:
  app:
    container_name: express
    restart: always
    environment:
      - DATABASE
      - DATABASE_USER
      - DATABASE_PASSWORD
    build: ./
    ports:
      - "80:5000"
    links:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    container_name: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U daria"]
      interval: 10s
      timeout: 5s
      retries: 5
    image: postgres
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - "54320:5432"
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
  nginx:
    build: ./nginx
    tty: true
    links:
      - app
      - postgres
    ports:
      - '8080:8080'