version: "3"
services:
  app:
    container_name: express
    restart: always
    build: ./
    ports:
      - "80:5000"
    volumes:
      - .:/app
    links:
      - postgres
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - "54320:5432"
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
  nginx:
    build: ./nginx
    tty: true
    links:
        - app
        - postgres
    ports:
        - '8080:8080'