version: 2.1
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: "Add environment variables to wait-for-it script and build Docker image"
          command: |
            echo DATABASE_USER=$DATABASE_USER
            echo DATABASE_PASSWORD=$DATABASE_PASSWORD
            echo DATABASE_HOSTNAME=$DATABASE_HOSTNAME
            echo DATABASE=$DATABASE
            echo DATABASE_USER=$DATABASE_USER | cat - wait-for-it.sh > temp && mv temp wait-for-it.sh
            echo DATABASE_PASSWORD=$DATABASE_PASSWORD | cat - wait-for-it.sh > temp && mv temp wait-for-it.sh
            echo DATABASE_HOSTNAME=$DATABASE_HOSTNAME | cat - wait-for-it.sh > temp && mv temp wait-for-it.sh
            echo DATABASE=$DATABASE | cat - wait-for-it.sh > temp && mv temp wait-for-it.sh
            echo '#!/bin/sh' | cat - wait-for-it.sh > temp && mv temp wait-for-it.sh
      - run:
          name: "Build application Docker image"
          command: |
            docker build --cache-from=app -t app .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar app
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/app.tar
      - deploy:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "docker-nginx" ]; then
              docker login --username=${DOCKER_HUB_USERNAME} --password=${DOCKER_HUB_PASSWORD}
              docker tag app "${DOCKER_HUB_USERNAME}/cinema_tracker_app:latest"
              docker push "${DOCKER_HUB_USERNAME}/cinema_tracker_app:latest"
              echo '145.239.86.60 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBMhC3TfusdIUXynfhRmZFrutCFxiMWw36+7lg5cAU9UzdsjpMentSJVtO86bULiX5G75lMiF+L7GziOUquIOW6I=' >> ~/.ssh/known_hosts
              ssh bartek@145.239.86.60 '~/update-app.sh'
            fi
