version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.15.2
    working_directory: ~/repo
    steps:
      - checkout
      - add_ssh_keys
      - run: |
          echo '145.239.86.60 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBMhC3TfusdIUXynfhRmZFrutCFxiMWw36+7lg5cAU9UzdsjpMentSJVtO86bULiX5G75lMiF+L7GziOUquIOW6I=' >> ~/.ssh/known_hosts
          ssh bartek@145.239.86.60 '~/update-app.sh'
